### ISSUE TITLE
A Question About the Functions.

### ISSUE THREAD

**Issue by BreezeShane** [coronaPolvo/PaperPlots#2]
Can it only print line chart now ? Then what else will be included ? 
If is OK, I can help to contribute some functions and encapsulate this project in the future.
And if Graph is necessary, NetworkX is available on PyPI. And PyEcharts is worthy to consider, too.

**Comment by AndSonder** [comment]
I will write a to-do list after my cryptography test. We can talk about your question after my test.

**Comment by AndSonder** [comment]
I plan to add more chart types. You will see the detail in the to-do list.
